import React,{useEffect,useState}from'react';import{api,mediaUrl}from'../api';import{DetailModal}from'../components/DataTable';import{formatIndianDate}from'../utils/format';
function DetectionEditor({d,onSaved,onUserView}:{d:any,onSaved:()=>void,onUserView:(u:any)=>void}){const[form,setForm]=useState({pest_id:d.pest_id||'',predicted_name:d.predicted_name||'',confidence:String(d.confidence||0),stage:d.stage||'',admin_note:d.admin_note||''});async function save(){try{await api.updateDetection(d.id,{...form,confidence:Number(form.confidence),admin_status:'corrected'});onSaved()}catch(e:any){alert(e.message)}}async function train(){try{await api.approveDetection(d.id,form.pest_id,form.stage);onSaved()}catch(e:any){alert(e.message)}}return <div className="detectCard"><img src={mediaUrl(d.image_url)}/><div className="detectBody"><div className="uploadMeta"><button className="linkBtn" onClick={()=>onUserView(d.user_details||{name:d.user_name,phone:d.user_phone})}>👨‍🌾 {d.user_name||'Unknown farmer'}</button><span>📅 {formatIndianDate(d.created_at)}</span></div><h3>{d.ai_response?.is_citrus_pest===false?'No citrus pest detected':d.predicted_name}</h3>{d.ai_response?.is_citrus_pest===false&&<p className="error">Negative response: review and correct if AI missed a pest.</p>}<p>Status: <b>{d.admin_status}</b> · {d.stage||'-'}</p><p><b>Reviewed by:</b> {d.reviewed_by_name || 'Not reviewed'} {d.reviewed_at ? `on ${formatIndianDate(d.reviewed_at)}` : ''}</p><p><b>AI Top:</b> {(d.ai_response?.top_k||[]).map((x:any)=>`${x.pest_name}`).join(', ')||'Data not available'}</p>
{d.ai_response?.decision && <div className="panel" style={{marginTop:8}}>
<h3>AI evidence (multi-stage pipeline)</h3>
<p><b>Decision:</b> {d.ai_response.decision} · <b>Review priority:</b> {d.ai_response.review_priority ?? '-'} · <b>Quality:</b> {d.ai_response.quality?.acceptable ? 'ok' : (d.ai_response.quality?.failed_checks||[]).join(', ')}</p>
<p><b>Signals:</b> {(d.ai_response.evidence?.signals||[]).map((s:any)=>`${s.source}: ${s.pest_id||'negative'} @ ${s.score}${s.weak?' (weak)':''}`).join(' · ')||'Data not available'}</p>
{d.ai_response.memory && <p><b>Visual memory (DINOv2+Qdrant):</b> top1 {d.ai_response.memory.top1?.pest_id ?? '-'} @ {d.ai_response.memory.top1_score} · support {d.ai_response.memory.support_count} · margin {d.ai_response.memory.margin}</p>}
{d.ai_response.clip && <p><b>OpenCLIP:</b> {d.ai_response.clip.top1?.pest_id ?? '-'} @ {d.ai_response.clip.top1?.score}</p>}
</div>}<div className="two"><input value={form.pest_id} onChange={e=>setForm({...form,pest_id:e.target.value})} placeholder="Correct pest id"/><input value={form.predicted_name} onChange={e=>setForm({...form,predicted_name:e.target.value})} placeholder="Correct response/name"/></div><div className="two"><input value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})} placeholder="Lifecycle stage"/><input value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value})} placeholder="Admin confidence 0-1"/></div><textarea value={form.admin_note} onChange={e=>setForm({...form,admin_note:e.target.value})} placeholder="Scientist/admin approved recommendation or correction note"/><button onClick={save}>Upload Correct Response</button><button className="secondary" onClick={train}>Approve & Train AI From This Upload</button></div></div>}
export function FarmerUploads(){const[items,setItems]=useState<any[]>([]);const[tab,setTab]=useState<'new'|'approved'>('new');const[err,setErr]=useState('');const[userView,setUserView]=useState<any>(null);const[queue,setQueue]=useState<any[]>([]);const load=()=>{api.detectionsToReview().then(setItems).catch((e:any)=>setErr(e.message));api.reviewQueue().then((r:any)=>setQueue(r.queue||[])).catch(()=>undefined)};useEffect(()=>{load()},[]);const newItems=items.filter(x=>!['approved_for_training','corrected'].includes(x.admin_status));const approved=items.filter(x=>['approved_for_training','corrected'].includes(x.admin_status));const shown=tab==='new'?newItems:approved;return <section><h2>Farmer Uploads: Images, AI Result & Corrections</h2>{err&&<p className="error">{err}</p>}
{queue.length>0&&<div className="panel"><h3>🎯 Priority review queue (active learning)</h3>
<p className="muted">The pipeline ranks unreviewed scans - label these first for the biggest accuracy gain.</p>
{queue.slice(0,8).map((q:any)=><div className="row" key={q.id}><img src={mediaUrl(q.image_url)} style={{width:56,height:56,borderRadius:12,objectFit:'cover',background:'#edf4e8'}}/><div style={{flex:1}}><b>{q.predicted_name}</b> <span className="muted">· {q.user_name||'farmer'}</span><br/><small>decision: {q.decision||'-'} · confidence {q.confidence}</small></div><span className="navBadge">{q.review_priority}</span></div>)}
</div>}
<div className="tabbar"><button className={tab==='new'?'activeTab':''} onClick={()=>setTab('new')}>New detections ({newItems.length})</button><button className={tab==='approved'?'activeTab':''} onClick={()=>setTab('approved')}>Approved / Corrected ({approved.length})</button></div>{shown.length===0&&<p className="panel">Data not available</p>}{shown.map(d=><DetectionEditor d={d} key={d.id} onSaved={load} onUserView={setUserView}/>) }<DetailModal row={userView} onClose={()=>setUserView(null)}/></section>}
