import React, { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { api } from '../api/client';
import { Screen } from '../components/Screen';
import { useI18n } from '../i18n';
const monthsEn = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const monthsMr = ['जाने','फेब्रु','मार्च','एप्रि','मे','जून','जुलै','ऑग','सप्टें','ऑक्टो','नोव्हें','डिसें'];
const monthsHi = ['जन','फर','मार्च','अप्रै','मई','जून','जुला','अग','सितं','अक्टू','नवं','दिसं'];
export function CalendarScreen() { const { t, lang } = useI18n(); const [items, setItems] = useState<any[]>([]); const [open,setOpen]=useState<number|null>(null); const [err,setErr]=useState(''); useEffect(() => { api.calendar(lang).then(setItems).catch((e:any)=>setErr(e.message)); }, [lang]); const months = lang==='mr'?monthsMr:lang==='hi'?monthsHi:monthsEn; return <Screen><Text style={styles.h1}>{t('calendarOperation')}</Text><Text style={styles.help}>{t('calendarHelp')}</Text>{err?<Text style={styles.error}>{err}</Text>:null}{items.length===0&&!err?<Text style={styles.empty}>{t('dataNotAvailable')}</Text>:null}{items.map(i => <Pressable key={i.month} style={styles.card} onPress={()=>setOpen(open===i.month?null:i.month)}><Text style={styles.month}>{months[i.month-1]}</Text><View style={{flex:1}}><Text style={styles.title}>{i.title}</Text>{open===i.month?<Text style={styles.desc}>{i.description}</Text>:<Text style={styles.tap}>{t('tapToView')}</Text>}</View></Pressable>)}</Screen>; }
const styles = StyleSheet.create({ h1: { fontSize: 26, fontWeight: '900', marginBottom: 4 }, help: { color: '#5b6b58', marginBottom: 14 }, error:{color:'#b00020',fontWeight:'800'}, empty:{backgroundColor:'white',padding:16,borderRadius:14,color:'#667'}, card: { flexDirection: 'row', gap: 14, backgroundColor: 'white', padding: 14, borderRadius: 16, marginBottom: 10, borderColor: '#e0efd8', borderWidth: 1 }, month: { width: 48, height: 48, textAlign: 'center', textAlignVertical: 'center', backgroundColor: '#116530', color: 'white', borderRadius: 14, overflow: 'hidden', fontWeight: '900', fontSize: 12 }, title: { fontWeight: '900', color: '#116530', fontSize: 16 }, desc: { color: '#40513d', marginTop: 6, lineHeight:20 }, tap:{color:'#7b8a77',marginTop:4,fontSize:12} });
