import React, { useState } from 'react';
import { Alert, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, setToken } from '../api/client';
import { registerPushTokenWithBackend } from '../push';
import { useI18n } from '../i18n';
const logo = require('../../assets/logo.png');

export function RegisterScreen({ onRegister }: any) {
  const { t } = useI18n();
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [district, setDistrict] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading,setLoading]=useState(false);
  async function submit() { try { setLoading(true); if (!name.trim()) throw new Error(t('nameRequired')); if (!phone.trim()) throw new Error(t('phoneRequired')); if (password.length < 6) throw new Error(t('passShort')); if (password !== confirmPassword) throw new Error(t('passMismatch')); const res = await api.register({ name, phone, password, confirm_password: confirmPassword, district } as any); setToken(res.access_token); await registerPushTokenWithBackend(); onRegister(); } catch (e: any) { Alert.alert(t('regFailed'), e.message || t('checkDetails')); } finally { setLoading(false); } }
  return <SafeAreaView style={styles.container}><View style={styles.card}><Image source={logo} style={styles.logo}/><Text style={styles.brand}>CitriSuraksha AI</Text><Text style={styles.h1}>{t('registerTitle')}</Text><TextInput style={styles.input} placeholder={t('fullName')} value={name} onChangeText={setName} /><TextInput style={styles.input} placeholder={t('phone')} keyboardType="phone-pad" value={phone} onChangeText={setPhone} /><TextInput style={styles.input} placeholder={t('district')} value={district} onChangeText={setDistrict} /><View style={styles.passWrap}><Text style={styles.lock}>🔒</Text><TextInput style={styles.passInput} placeholder={t('passwordPh')} secureTextEntry={!showPassword} value={password} onChangeText={setPassword} /><Pressable onPress={() => setShowPassword(!showPassword)}><Text style={styles.show}>{showPassword ? '🙈' : '👁️'}</Text></Pressable></View><TextInput style={styles.input} placeholder={t('confirmPh')} secureTextEntry={!showPassword} value={confirmPassword} onChangeText={setConfirmPassword} /><Pressable style={[styles.button,loading&&{opacity:.7}]} disabled={loading} onPress={submit}><Text style={styles.buttonText}>{loading?t('pleaseWait'):t('registerBtn')}</Text></Pressable></View></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, padding: 20, justifyContent: 'center', backgroundColor: '#050805' }, card: { backgroundColor: 'white', borderRadius: 28, padding: 22, borderWidth: 1, borderColor: '#e0efd8' }, logo:{width:120,height:120,borderRadius:24,alignSelf:'center',marginBottom:8}, brand:{textAlign:'center',color:'#116530',fontSize:24,fontWeight:'900',marginBottom:8}, h1: { fontSize: 24, fontWeight: '900', marginBottom: 14 }, input: { backgroundColor: '#fbfff8', borderColor: '#d5e8d0', borderWidth: 1, padding: 14, borderRadius: 12, marginBottom: 12 }, passWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fbfff8', borderColor: '#d5e8d0', borderWidth: 1, borderRadius: 12, marginBottom: 12, paddingRight: 12 }, lock:{paddingLeft:12}, passInput: { flex: 1, padding: 14 }, show: { color: '#116530', fontWeight: '900', fontSize:20 }, button: { backgroundColor: '#116530', padding: 16, borderRadius: 14, alignItems: 'center', marginTop: 8 }, buttonText: { color: 'white', fontWeight: '900' } });
